---
- name: create glance database
  mysql_db: login_user=root login_password={{ root_dbpw }} name=glance state=present
  when: inventory_hostname == 'controller1'

- name: grant glance database local host access
  mysql_user: login_user=root login_password={{ root_dbpw }} name=glance password={{ glance_dbpw }} priv='glance.*:ALL'
  when: inventory_hostname == 'controller1'

- name: grant glance database controller1 host access
  mysql_user: login_user=root login_password={{ root_dbpw }} name=glance password={{ glance_dbpw }} priv='glance.*:ALL' host=controller1
  when: inventory_hostname == 'controller1'

- name: grant glance database controller2 host access
  mysql_user: login_user=root login_password={{ root_dbpw }} name=glance password={{ glance_dbpw }} priv='glance.*:ALL' host=controller2
  when: inventory_hostname == 'controller1'

- name: grant glance database controller3 host access
  mysql_user: login_user=root login_password={{ root_dbpw }} name=glance password={{ glance_dbpw }} priv='glance.*:ALL' host=controller3
  when: inventory_hostname == 'controller1'

- name: grant glance database any host access
  mysql_user: login_user=root login_password={{ root_dbpw }} name=glance password={{ glance_dbpw }} priv='glance.*:ALL' host=%
  when: inventory_hostname == 'controller1'

- name: create glance user
  os_user: cloud=openstack state=present name=glance password={{ glance_pw }} update_password=on_create domain=default default_project=admin
  when: inventory_hostname == 'controller1'

- name: grant admin role on the glance user
  os_user_role: cloud=openstack user=glance role=admin project=service
  when: inventory_hostname == 'controller1'

- name: create glance service
  os_keystone_service: cloud=openstack state=present name=glance service_type=image description="OpenStack Image Service"
  when: inventory_hostname == 'controller1'

- name: create glance public endpoint
  os_keystone_endpoint: cloud=openstack service=glance endpoint_interface=public url=http://{{ vip }}:9292 region=RegionOne state=present
  when: inventory_hostname == 'controller1'

- name: create glance internal endpoint
  os_keystone_endpoint: cloud=openstack service=glance endpoint_interface=internal url=http://{{ vip }}:9292 region=RegionOne state=present
  when: inventory_hostname == 'controller1'

- name: create glance admin endpoint
  os_keystone_endpoint: cloud=openstack service=glance endpoint_interface=admin url=http://{{ vip }}:9292 region=RegionOne state=present
  when: inventory_hostname == 'controller1'

- name: install glance package
  yum: name=openstack-glance state=latest

- name: create glance-api configuration file
  template: src=glance-api.conf.j2 dest=/etc/glance/glance-api.conf
  notify: restart glance services

- name: create glance-registry configuration file
  template: src=glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf
  notify: restart glance services

- name: create ansible temporary directory
  file: path=/var/lib/glance/.ansible/tmp state=directory mode=0755
  become: yes
  become_user: glance
  when: inventory_hostname == 'controller1'

- name: populate glance database
  shell: glance-manage db_sync
  become: yes
  become_user: glance
  when: inventory_hostname == 'controller1'
  register: command_result
  failed_when:
    - "'FAIL' in command_result.stderr"

- name: start glance-api service
  service: name=openstack-glance-api state=started enabled=yes

- name: start glance-registry service
  service: name=openstack-glance-registry state=started enabled=yes

