---
- name: install haproxy package
  yum: name=haproxy state=latest

- name: create haproxy configuration file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: start haproxy service
  service: name=haproxy state=started enabled=yes