---
- name: create clustercheck configuration file
  template: src=clustercheck.j2 dest=/etc/sysconfig/clustercheck
  notify: restart xinetd

- name: set clustercheck user password
  mysql_user: login_user=root login_password={{ root_dbpw }} name=clustercheck password={{ clustercheck_dbpw }} priv='*.*:PROCESS'

- name: create galera-monitor service configuration file
  template: src=galera-monitor.j2 dest=/etc/xinetd.d/galera-monitor
  notify: restart xinetd

- name: start xinetd service
  service: name=xinetd state=started enabled=yes
